import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import type { Metadata } from 'next/'
import { Roboto } from 'next/font/google'
import './globals.css'
import TabComponent from './TabComponent'

const roboto = Roboto({
	weight: ['300', '400', '500', '700'],
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-roboto',
})
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' className={roboto.variable}>
			<body className='antialiased p-5'>
				<AppRouterCacheProvider options={{ key: 'css' }}>
					<TabComponent />
					{children}
				</AppRouterCacheProvider>
			</body>
		</html>
	)
}
